steps:
  - name: gcr.io/cloud-builders/yarn:node-12.18.3
    dir: frontend
    args:
      - install
  - name: gcr.io/cloud-builders/yarn
    dir: frontend
    args:
      - build
  - name: bash
    dir: frontend
    args:
      - -c
      - |
        cat <<EOT > .env
        GCP_PROJECT=$PROJECT_ID
        REGION=$_REGION
        REGISTRY_ID=$_REGISTRY_ID
        TZ=Asia/Tokyo
        EOT
    env:
      - GCP_PROJECT=$PROJECT_ID
      - REGION=$_REGION
      - REGISTRY_ID=$_REGISTRY_ID
  - name: gcr.io/cloud-builders/gcloud
    dir: frontend
    args:
      - app
      - deploy
      - --quiet
