- name: Clone a repo
  ansible.builtin.git:
    repo: https://github.com/mukopikmin/interphone-watcher.git
    dest: /home/pi/interphone-watcher
- name: Create venv
  ansible.builtin.shell:
    cmd: python3 -m venv venv
    chdir: /home/pi/interphone-watcher/device
- name: Install pacakages with pip
  ansible.builtin.pip:
    requirements: /home/pi/interphone-watcher/device/requirements.txt
    virtualenv: /home/pi/interphone-watcher/device/venv
- name: Create service for temperature agent
  become: yes
  ansible.builtin.file:
    dest: /etc/systemd/system/temperature-agent.service
    src: /home/pi/interphone-watcher/device/services/temperature-agent.service
    state: link
- name: Make sure a service is running
  become: yes
  ansible.builtin.systemd:
    state: started
    enabled: yes
    name: temperature-agent
    daemon_reload: yes
