- name: Set daily reboot
  ansible.builtin.cron:
    name: 'daily reboot'
    minute: '0'
    hour: '2'
    job: 'touch /home/pi/rebooted && reboot'
- name: Set timezone to Asia/Tokyo
  become: yes
  community.general.timezone:
    name: Asia/Tokyo
- name: Install apt packages
  become: yes
  ansible.builtin.apt:
    pkg:
      - git
      - vim
      - python3
      - python3-venv
      - python-setuptools
      - libatlas-base-dev
    update_cache: yes
